### ISSUE TITLE
TS issue when using as an NPM script in Ubuntu

### ISSUE THREAD

**Issue by michael-siek** [straker/browser-driver-manager#6]
It looks like when trying to use this as an NPM script in Ubuntu CI there is a type issue where `cursorTo()` is not a function.

```console
process.stdout.cursorTo(lastChunk.length - 1);
                       ^
TypeError: process.stdout.cursorTo is not a function
```

**Comment by straker** [comment]
Hu. What version of node is the Ubuntu CI running? I can't find any docs for `stdout.cursorTo`, but it [might have been deprecated](https://github.com/nodejs/node/issues/9853) and so they didn't ever add docs?

I'll see if the replacement [tty](https://nodejs.org/api/tty.html) could work? But it says that `tty.WriteSteam`:

> Represents the writable side of a TTY. In normal circumstances, [process.stdout](https://nodejs.org/api/process.html#processstdout) and [process.stderr](https://nodejs.org/api/process.html#processstderr) will be the only tty.WriteStream instances created for a Node.js process and there should be no reason to create additional instances.

So I'm not sure why `process.stdout`, which supposedly is a `tty.WriteStream` instance, wouldn't have `cursorTo`

**Comment by michael-siek** [comment]
closing I don't think this is required anymore
